
name: Push

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with: { java-version: 21, distribution: temurin, cache: maven }
      - name: Build Project
        run: ./mvnw install
